name: Build status
on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Docs build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        task: ['pycodestyle']
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools
        pip install -r docs/requirements.txt
    - name: Run Beefore checks
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd docs && make html
